### ISSUE TITLE
Entity Security Role Freezes

### ISSUE THREAD

**Issue by rduz** [santoshCRM/EntitySecurityRole#2]
Hi,

XrmToolBox version is 1.2018.10.29.
EntitySecurityRole version is 1.2018.6.19

Entity Security Role is freezing for long periods of time.  I've found that if I Retrieve Entities, then click in the 'security role' tab on the right side of the window, ESR will be unresponsive for several minutes.   It eventually, usually, starts responding again, but sometimes the plugin crashes.  We have only one business unit and perhaps 50 total roles.

![image](https://user-images.githubusercontent.com/956908/53906603-ff656400-4010-11e9-95fd-69ab7a78dedc.png)

What can I do on my end to help figure out what the problem might be?

**Comment by santoshCRM** [comment]
This issue is resolved in version 1.2019.11.21
