### ISSUE TITLE
Error when loading entities

### ISSUE THREAD

**Issue by nic07crm** [santoshCRM/EntitySecurityRole#3]
When I click on the Retrieve Entities button I receive the following error

![image](https://user-images.githubusercontent.com/55504937/65167574-7213bb00-da08-11e9-8783-5b21933b5b6c.png)
![2019-09-18_11-32-27](https://user-images.githubusercontent.com/55504937/65167631-8ce62f80-da08-11e9-9e67-e70023b7dea8.jpg)

**Comment by santoshCRM** [comment]
Connection is update with version 1.2018.6.20
